name: FitnessPlace
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.6+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3
  google_fonts: ^0.3.5
  #sticky_and_expandable_list: ^1.0.2
  sticky_headers: "^0.1.8"
  intl: ^0.16.1
  http: ^0.12.0+2
  flutter_secure_storage: ^3.3.5
  connectivity: ^2.0.2
  shared_preferences: ^0.5.12+4
  #archive: ^2.0.13

dev_dependencies:
  flutter_launcher_icons: "^0.8.0"
  flutter_test:
    sdk: flutter

flutter_icons:
  ios: true
  image_path: "assets/icon.jpeg"
  adaptive_icon_background: "#191919"
  adaptive_icon_foreground: "assets/img/Diane.JPG"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - ./assets/img/BackgroundImg.jpeg
    - ./assets/img/IMG_0118.JPG
    - ./assets/img/IMG_7817.JPG
    - ./assets/img/IMG_8441.JPG
    - ./assets/img/IMG_8565.JPG
    - ./assets/img/output.JPG
    - ./assets/img/Diane.JPG
    - ./assets/img/logo.jpeg
    - ./assets/img/7EBC215E-30C2-49BE-B5E4-F46826F959DE.jpeg
    - ./assets/img/8E053972-17A0-4DE1-99A9-968C32BDF6C1.jpeg
    - ./assets/img/12599F3D-41E0-4F10-BA8A-0C04E51378F0.jpeg
    - ./assets/img/100353E2-DC6E-423A-99A2-F49AFA80BA81.jpeg
    - ./assets/img/B1F6542E-07E0-4BA1-BA39-CF009393A2A9.jpeg
    - ./assets/img/D7B9A39D-5E12-4D86-840F-ACFF54AE36CB.jpeg
    - ./assets/img/EB84B7AE-F621-4AC3-86CC-3B3078C28BFB.jpeg
    - ./assets/avatar/img.png
    - ./assets/img/F0345748-C3FC-4BDD-87E2-E1266AFBE06B_4_5005_c.jpeg

  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
